services:
  # Service de l'Application Spring Boot connecté à Supabase
  app-ega:
    build: .
    container_name: spring-ega
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.vicuxzdqtqhiozotrevg:egabackendDJ@bar00@aws-0-eu-west-1.pooler.supabase.com:6543/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SUPER_ADMIN_USERNAME=superadmin
      - SUPER_ADMIN_PASSWORD=SuperAdminSecurePassword123!
      - SUPER_ADMIN_EMAIL=admin@ega.local
      - SUPER_ADMIN_NOM=EGA
      - SUPER_ADMIN_PRENOM=SuperAdmin
      - SUPER_ADMIN_NUMERO=+221770000000
    restart: always
